name: Vacation Mode
on:
  # Run on issue activity
  issues:
  # Run to reset the 24 hour interaction limit timer
  schedule:
    - cron: "0 0 * * *"

jobs:
  vacation_mode_job:
    runs-on: ubuntu-latest
    name: Update Vacation Mode
    steps:
    - uses: robotnyc/vacation-mode-action@v1
      with:
        limit-group: 'collaborators_only'
        vacation-mode-activated: '![vacation-mode-activated](https://i.imgflip.com/18t5ch.jpg)'
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
